<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Roll\'n API')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/bower_components/bootstrap/dist/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/bower_components/bootstrap/dist/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/bower_components/bootstrap/dist/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/bower_components/jquery/dist/jquery.min.js')
        ; ?>

    </head>
    <body>

<style>
.rollnapi {
    color: black;
    text-shadow: none;
    border-color: white;
    background-image: linear-gradient(to bottom, #51A5BD 0px, #A3D1FF 100%)
}

.rollnapi {
}
</style>

        <nav class="navbar navbar-inverse navbar-fixed-top rollnapi" role="navigation">
            <div class="container">
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav rollnapi">
                        <li class="rollnapi"><a href="/">Home</a></li>
                        <li class="rollnapi"><a href="/about">About Roll'n API</a></li>
                        <li class="rollnapi"><a href="https://about.me/tom_h_anderson">About Tom Anderson</a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>

        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy;<?php echo date('Y') ?> <a href="mailto:tom.h.anderson@gmail.com">Roll'n API</a> <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
