<div style="margin-top: 60px" class="jumbotron">
    Roll'n API is a 30 minute talk by <a href="https://about.me/tom_h_anderson">Tom Anderson</a>
    in which a 100% Doctrine 2 API with OAuth2 authentication
    is created beginning with the ORM design tool <a href="http://www.skipper18.com">Skipper</a>
    and built to a fully functional and secured API.  Coding is executed live and there are no slides.
</div>

<h1>Presentations</h1>

<h2>2014-02-10 PHP Meetup in San Francisco</h2>

Given to an audience of about 30, the entire talk is recorded here:<br>
<iframe width="560" height="315" src="//www.youtube.com/embed/5apFQF3VE3M" frameborder="0" allowfullscreen></iframe>

