<div class="conatiner">
    <h1><?php echo sprintf($this->translate('Roll\'n API'), '<span class="color-orange">', '</span>') ?></h1>
    <p>
    This website is the companion to a talk detailing how to build a Doctrine ORM OAuth2 API with
    Apigility. Concepts covered are
    <a href="http://en.wikipedia.org/wiki/Object-relational_mapping">ORM</a>,
    <a href="http://stateless.co/hal_specification.html">HAL</a>,
    <a href="http://framework.zend.com/">ZF2</a>,
    <a href="http://www.doctrine-project.org/">Doctrine 2</a>,
    <a href="http://apigility.org/">Apigility</a>, and
    <a href="http://www.skipper18.com/">Skipper</a>
    using the
    <a href="https://github.com/zfcampus/zf-apigility-doctrine">Apigility Doctrine integration module for Apigility</a>.
    <a href="/about">More Info...</a>
    </p>
</div>

<h1>The Entity Relationship Diagram</h1>
If you have <a href="http://www.skipper18.com">Skipper</a> then <a href="https://github.com/TomHAnderson/RollnApi">here is the skipper ERD file</a>.
<br>

<img src="/img/erd.png">

<h1>Running tests against the demo API</h1>
<p>
This website is running the Roll'n API API.  See the See <a href="https://github.com/TomHAnderson/RollnApi/blob/master/docs/LIVE_TESTING.md">Live API Testing Guide</a>
to try it out.
</p>

<h1>Installing the completed API</h1>

<div class="container">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('1. Clone the project') ?></h3>
            </div>
            <div class="panel-body">
                <p>Using <a href="http://git-scm.com/">git</a>, fork <a href="https://github.com/TomHAnderson/RollnApi">the RollnApi project</a>
                to your github account
                then clone the repository locally.  The root directory of your cloned copy will hereafter be referred to as ~</p>
            </div>
        </div>
    </div>

    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('2. Create the database and run') ?></h3>
            </div>
            <div class="panel-body">
                <p>
                    cd to ~ and run
                    <p>
                        <b>
                        php public/index.php orm:schema-tool:create
                        <br>
                        php public/index.php data-fixture:import
                        </b>
                    </p>

                    Now run the application.  With php 5.4 you can use:
                    <p>
                        <b>php -S localhost:8083 -t public/ public/index.php</b>
                    </p>
                </p>
            </div>
        </div>
    </div>


    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('3. Run All API tests') ?></h3>
            </div>
            <div class="panel-body">
                See <a href="https://github.com/TomHAnderson/RollnApi/blob/master/docs/API_TESTING.md">API Testing Guide</a>
            </div>
        </div>
    </div>

</div>
